const SUPABASE_URL = 'https://enbghqraldttcqdzzhdx.supabase.co';
const SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVuYmdocXJhbGR0dGNxZHp6aGR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg2NzEwNDIsImV4cCI6MjA5NDI0NzA0Mn0.AiwKt87lu47bWLRUoRi4wzO0TFMoo6AY6TLhlH-_bXM';
